version: "3.7"

services:
  app:
    image: go-template/app
    depends_on: [ db ]
    container_name: app
    build: .
    ports: [ "8080:33333" ]
    restart: always
    volumes: [ fs_data:/data ]
    env_file: .env
    environment:
      - SUPER_SECRET=123456
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
volumes:
  db_data: { }
  fs_data: { }